spring.application.name=web_socket_step
server.port=8080

# 0. UTF-8 ??
# ? ??? ???? UTF-8? ?? ???.
# ?? ?? ?? ??
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true


# 1. DB ??
# datasource ?? ???? (??? ??? ?? ?? ??)
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa

# 2. hibernate ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mustache.cache=false