spring:
  mustache:
    suffix: .mustache
    prefix: classpath:/templates/
    charset: UTF-8
    servlet:
      cache: false

  h2:
    console:
      enabled: false

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
