spring:
  profiles:
    active:
      - dev
#      - local
      - secret
#        dev -> mysql
#        local -> h2-console
file:
  upload:
    path: ${FILE_UPLOAD_PATH}


logging:
  level:
    root: info
    org.example.shopping: debug